services:
  - type: web
    name: telegram-bot
    env: python:3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WC_KEY
        sync: false
      - key: WC_SECRET
        sync: false
